### ISSUE TITLE
Debug & Docker Compose - host ip vs network gateway

### ISSUE THREAD

**Issue by aabes** [ruby-debug/ruby-debug-ide#101]
Setup:
 Host: OSX. Docker 17.06 mac.
 Rails environment built into docker-compose (which means, it's setup with private network). see below.

Issue:
 When connecting a InelliJU debug session to a waiting debug session inside the container, breakpoints hit on the master process (of zeus) but not on child processes.

Using Strace, it seems that the forked child is attempting to connect to the gateway address as seen from the container, rather than the host address.
Looking at code a bit around [here](https://github.com/ruby-debug/ruby-debug-ide/blob/master/lib/ruby-debug-ide.rb#L120)  seems DEBUGGER_HOST is set based on the network info. 
This results in the child not connecting to the IDE, and no breakpoints being configured.

Seems that if there was a way to pass an override environment variable as to where the IDE is (the host computer, then the child could connect and apply breakpoints?

Debugger invocation:
./bin/rdebug-ide -d --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- /cht/app/bin/zeus start --log zeus.log

```
 web:
    build:
      context: ../
      dockerfile: Dockerfile-sandbox
    privileged: true
    links:
      - redis
      - mysql
      - elastic
      - rabbitmq
    volumes:
      - ../:/app/
      - bundle:/cht/app/bundle 
    environment:
      - LOCAL_HOST=192.168.31.3
    ports:
      - target: 3000
        published: 3000
        mode: host
        ### For Debugging
      - target: 1234
        published: 1234
        mode: host
```
