### ISSUE TITLE
RubyMine: Termination timed out worker: 

### ISSUE THREAD

**Issue by chuenniger** [ruby-debug/ruby-debug-ide#182]
Hi

I´ve a problem to debug my application in docker. My setup is correct I think because without debugger everything works fine.

Ports
```yaml
command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "1234:1234"
      - "26162:26162"
      - "26168:26168"
```

The error: (The site is not responding)
```
Fast Debugger (ruby-debug-ide 0.7.0, debase 0.2.4.1, file filtering is supported) listens on 0.0.0.0:1234
=> Booting Puma
=> Rails 5.2.3 application starting in development 
=> Run `rails server -h` for more startup options
[8] Puma starting in cluster mode...
[8] * Version 4.0.1 (ruby 2.6.2-p47), codename: 4 Fast 4 Furious
[8] * Min threads: 5, max threads: 5
[8] * Environment: development
[8] * Process workers: 2
[8] * Preloading application
[8] * Listening on tcp://0.0.0.0:3000
[8] Use Ctrl-C to stop
[8] ! Terminating timed out worker: 16
[8] ! Terminating timed out worker: 18
[8] ! Terminating timed out worker: 20
[8] ! Terminating timed out worker: 21
[8] ! Terminating timed out worker: 24
[8] ! Terminating timed out worker: 25
[8] ! Terminating timed out worker: 28
[8] ! Terminating timed out worker: 29
```

![Screenshot 2019-11-26 at 09 12 34](https://user-images.githubusercontent.com/188438/69610835-e54f3400-102c-11ea-9fc0-67c03acbdffb.png)
![Screenshot 2019-11-26 at 09 12 58](https://user-images.githubusercontent.com/188438/69610859-f1d38c80-102c-11ea-9544-5dd9d2a4bca3.png)
