### ISSUE TITLE
Undefined method `frame_pos` on Debase object

### ISSUE THREAD

**Issue by tyler-ball** [ruby-debug/ruby-debug-ide#63]
Stacktrace:

```
637: Exception in DebugThread loop: undefined method `frame_pos' for #<Debase::ControlState:0x007fc8bd3f68c0>(NoMethodError)
Backtrace:
/Users/tball/.rvm/gems/ruby-2.1.4@global/gems/ruby-debug-ide-0.4.23.beta11/lib/ruby-debug-ide/commands/frame.rb:41:in `execute'
  from: /Users/tball/.rvm/gems/ruby-2.1.4@global/gems/ruby-debug-ide-0.4.23.beta11/lib/ruby-debug-ide/ide_processor.rb:90:in `block in process_commands'
  from: /Users/tball/.rvm/gems/ruby-2.1.4@global/gems/ruby-debug-ide-0.4.23.beta11/lib/ruby-debug-ide/ide_processor.rb:87:in `catch'
  from: /Users/tball/.rvm/gems/ruby-2.1.4@global/gems/ruby-debug-ide-0.4.23.beta11/lib/ruby-debug-ide/ide_processor.rb:87:in `process_commands'
  from: /Users/tball/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.4.23.beta11/lib/ruby-debug-ide.rb:124:in `block in start_control'
```

I got this trying to debug a Chef cookbook earlier, using the beta11 of ruby-debug-ide and 0.1.0 of debase in the latest version of Rubymine for OSX Yosemite.  Ruby is 2.1.4 installed with RVM.  I haven't seen this before when debugging Chef cookbooks.

I'm manually pinning the gem versions in my gemspec so that I can run `rvmsudo bundle exec rdebug-ide --host 0.0.0.0 --port 58959 --dispatcher-port 58960 -- ./bin/chef-client`.  I need to run this in rvmsudo because Chef needs sudo permissions to install packages.  I know that rvmsudo can mess up the environment some (`Dir.getwd` comes back as `/` when I am not executing the command from there).

Let me know what other debugging information I can provide.
